# To be run preferably in batch, without graphics:
# ./How-To-Geant4 run.mac
#

#Silence hadronic process summary (works in Geant4 v10.7.1)
#/control/verbose 0
#/run/verbose 0
#/process/had/verbose 0
#/process/verbose 0
#/process/em/verbose 0

#Set number of worker threads and initialize run
/run/numberOfThreads 4
/run/initialize

#BEAM
#------------------------------------------------------------------------
#execute the macro file which defines the primary particle
#/control/execute ../Macros/Primary_Alpha.mac        #52 MeV Alpha Beam, point source
#/control/execute ../Macros/Primary_Deuteron.mac     #26 MeV Deuteron Beam, point source
#/control/execute ../Macros/Primary_Neutron.mac      #13 MeV Neutron Beam, point source
#/control/execute ../Macros/Primary_Proton.mac       #13 MeV Proton Beam, point source
#/control/execute ../ClusterMacros/AmBe/Shielding/Primary_AmBe.mac         #AmBe Neutron Source, point source
#/control/execute ../Macros/Primary_Radionuclide.mac #Radionuclide Source, point source
/control/execute ../Macros/Primary_Nitrogen.mac        #17N5+ Nitrogen beam, point source


#set material
#/custom/geo/setMat G4_Al
/custom/geo/setMat G4_AIR
#/custom/geo/setMat G4_GRAPHITE

#Start a run and print progress in console
#1st energy
#/gps/ene/mono 140. MeV
#/custom/ana/setOutFolder Output/range_N_140_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#2nd energy
#/gps/ene/mono 130. MeV
#/custom/ana/setOutFolder Output/range_N_130_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#3rd energy
#/gps/ene/mono 120. MeV
#/custom/ana/setOutFolder Output/range_N_120_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#4th energy
#/gps/ene/mono 110. MeV
#/custom/ana/setOutFolder Output/range_N_110_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#5th energy
#/gps/ene/mono 100. MeV
#/custom/ana/setOutFolder Output/range_N_100_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#6th energy
#/gps/ene/mono 90. MeV
#/custom/ana/setOutFolder Output/range_N_090_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#7th energy
#/gps/ene/mono 80. MeV
#/custom/ana/setOutFolder Output/range_N_080_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#8th energy
/gps/ene/mono 70. MeV
/custom/ana/setOutFolder Output/range_N_070_MeV_G4_Air
/run/printProgress 100
/run/beamOn 100000

#9th energy
#/gps/ene/mono 60. MeV
#/custom/ana/setOutFolder Output/range_N_060_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#10th energy
#/gps/ene/mono 50. MeV
#/custom/ana/setOutFolder Output/range_N_050_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#11th energy
#/gps/ene/mono 40. MeV
#/custom/ana/setOutFolder Output/range_N_040_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#12th energy
#/gps/ene/mono 30. MeV
#/custom/ana/setOutFolder Output/range_N_030_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#13th energy
#/gps/ene/mono 20. MeV
#/custom/ana/setOutFolder Output/range_N_020_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#14th energy
#/gps/ene/mono 10. MeV
#/custom/ana/setOutFolder Output/range_N_010_MeV_G4_Air
#/run/printProgress 100
#/run/beamOn 100000

#max value for beam On is 2.147.483.647 because this is the maximum value for a 32 bit integer
