#Set number of worker threads and initialize run
/run/numberOfThreads 4
/run/initialize

#BEAM
#------------------------------------------------------------------------
#Commands to use with the General Particle Source (GPS)

/gps/particle proton    #beam particle
/gps/position 0 0 -1 cm      #GPS position
/gps/direction 0 0 1     #oriented along the Z axis
/gps/ene/type Mono       #monoenergetic:   I=E
gps/ene/mono 13. MeV   #sets energy for monoenergetic sources
#/gps/pos/type Point 

#/gps/pos/shape Circle    #the beam geometry is a circle
#/gps/pos/radius 0. mm

#HISKP Cyclotron FWHM is approx 4mm. FWHM = 2.3548*sigma -> sigma = 1.79mm
#/gps/pos/sigma_r 1.79 mm
#/gps/pos/sigma_r 4. mm
#/gps/pos/type Beam
#------------------------------------------------------------------------

#custom commands to change things
#/custom/geo/change_a 15 cm
#/custom/geo/change_b 15 cm
#/custom/geo/change_c 15 cm
#/custom/geo/change_d 15 cm
#/custom/geo/change_e 15 cm
#/custom/geo/setMat G4_Al
#/custom/ana/setOutFolder C-Target_D26

/custom/geo/change_e 1.2 mm
/custom/geo/setMat G4_Al
/custom/ana/setOutFolder Output/D_G4_Al_26MeV_tny
/gps/particle proton
/gps/ene/mono 13. MeV

#Start a run and print progress in console
/run/printProgress 10000
/run/beamOn 10000000

#max value for beam On is 2.147.483.647 because this is the maximum value for a 32 bit integer
