# To be run preferably in batch, without graphics:
# ./How-To-Geant4 run.mac
#

#Silence hadronic process summary (works in Geant4 v10.7.1)
#/control/verbose 0
#/run/verbose 0
#/process/had/verbose 0
#/process/verbose 0
#/process/em/verbose 0

#Set number of worker threads and initialize run
/run/numberOfThreads 4
/run/initialize

#BEAM
#------------------------------------------------------------------------
#execute the macro file which defines the primary particle
#/control/execute ../Macros/Primary_Alpha.mac        #52 MeV Alpha Beam, point source
#/control/execute ../Macros/Primary_Deuteron.mac     #26 MeV Deuteron Beam, point source
#/control/execute ../Macros/Primary_Neutron.mac      #13 MeV Neutron Beam, point source
#/control/execute ../Macros/Primary_Proton.mac       #13 MeV Proton Beam, point source
#/control/execute ../ClusterMacros/AmBe/Shielding/Primary_AmBe.mac         #AmBe Neutron Source, point source
#/control/execute ../Macros/Primary_Radionuclide.mac #Radionuclide Source, point source
/control/execute ../Macros/Primary_Nitrogen.mac        #17N5+ Nitrogen beam, point source


#set material
/custom/geo/setMat G4_Al
#/custom/geo/setMat G4_AIR
#/custom/geo/setMat G4_GRAPHITE

#Start a run and print progress in console
/gps/ene/mono 100. MeV
/custom/ana/setOutFolder Output/sandwich_N_100_MeV_G4_Al_G4_AIR_G4_Al
/run/printProgress 100
/run/beamOn 100000



#max value for beam On is 2.147.483.647 because this is the maximum value for a 32 bit integer
