#AMBE NEUTRON SOURCE
#------------------------------------------------------------------------
#From the Docs:
#There is also the option for the user to define a histogram in energy (“User”) ... that can be fit with various simple functions.
#The data for histograms or point spectra must be provided in ascending bin (abscissa) order.
#The point-wise spectrum may be differential (as with a binned histogram).
#The maximum energy of an integral spectrum is defined by the last-but-one data point, because GPS converts to a differential spectrum internally.
#The histogram is loaded, one bin at a time, by using the /gps/hist/point command, 
#followed by its two arguments the upper boundary of the bin and the weight (or area) of the bin.
#Currently histograms are limited to 1024 bins.
#The first value of each user input data pair is treated as the upper edge of the histogram bin and the second value is the bin content. 
#The exception is the very first data pair the user input whose first value is the treated as the lower edge of the first bin of the histogram,
# and the second value is not used. 
#This rule applies to all distribution histograms, as well as histograms for biasing.


#AmBe energy Spectrum for small sources according to ISO 8529-1-2021
/gps/particle neutron        #beam particle
/gps/position 0 0 -10 cm     #GPS position
#/gps/direction 0 0 1        #oriented along the Z axis
/gps/pos/type Point
/gps/ang/type iso
/gps/ang/mintheta 100 degree
/gps/ene/type User
/gps/hist/type energy
/gps/hist/point 0. 0.
/gps/hist/point 4.223E-9	0.000E+0
/gps/hist/point 1.334E-8	2.509E-7
/gps/hist/point 4.212E-8	8.739E-7
/gps/hist/point 1.330E-7	2.275E-6
/gps/hist/point 4.201E-7	5.057E-6
/gps/hist/point 1.327E-6	9.375E-6
/gps/hist/point 4.190E-6	1.742E-5
/gps/hist/point 1.323E-5	3.253E-5
/gps/hist/point 4.179E-5	6.107E-5
/gps/hist/point 1.320E-4	1.148E-4
/gps/hist/point 4.168E-4	2.168E-4
/gps/hist/point 1.316E-3	4.128E-4
/gps/hist/point 4.158E-3	8.113E-4
/gps/hist/point 1.313E-2	1.752E-3
/gps/hist/point 4.147E-2	4.646E-3
/gps/hist/point 1.171E-1	1.012E-2
/gps/hist/point 3.204E-1	2.413E-2
/gps/hist/point 5.236E-1	2.940E-2
/gps/hist/point 7.269E-1	2.643E-2
/gps/hist/point 9.302E-1	2.406E-2
/gps/hist/point 1.133E+0	1.944E-2
/gps/hist/point 1.337E+0	1.845E-2
/gps/hist/point 1.540E+0	1.880E-2
/gps/hist/point 1.743E+0	1.781E-2
/gps/hist/point 1.947E+0	1.655E-2
/gps/hist/point 2.150E+0	2.088E-2
/gps/hist/point 2.353E+0	2.381E-2
/gps/hist/point 2.556E+0	2.179E-2
/gps/hist/point 2.760E+0	2.337E-2
/gps/hist/point 2.963E+0	3.089E-2
/gps/hist/point 3.166E+0	3.876E-2
/gps/hist/point 3.370E+0	3.750E-2
/gps/hist/point 3.573E+0	3.228E-2
/gps/hist/point 3.776E+0	2.996E-2
/gps/hist/point 3.979E+0	2.832E-2
/gps/hist/point 4.183E+0	2.797E-2
/gps/hist/point 4.386E+0	2.851E-2
/gps/hist/point 4.589E+0	2.523E-2
/gps/hist/point 4.793E+0	2.944E-2
/gps/hist/point 4.996E+0	3.157E-2
/gps/hist/point 5.199E+0	3.070E-2
/gps/hist/point 5.402E+0	2.588E-2
/gps/hist/point 5.606E+0	2.472E-2
/gps/hist/point 5.809E+0	2.125E-2
/gps/hist/point 6.012E+0	1.686E-2
/gps/hist/point 6.215E+0	1.563E-2
/gps/hist/point 6.419E+0	1.907E-2
/gps/hist/point 6.622E+0	1.821E-2
/gps/hist/point 6.825E+0	1.639E-2
/gps/hist/point 7.029E+0	1.421E-2
/gps/hist/point 7.232E+0	1.411E-2
/gps/hist/point 7.435E+0	1.660E-2
/gps/hist/point 7.638E+0	1.688E-2
/gps/hist/point 7.842E+0	1.853E-2
/gps/hist/point 8.045E+0	1.580E-2
/gps/hist/point 8.248E+0	1.123E-2
/gps/hist/point 8.452E+0	1.036E-2
/gps/hist/point 8.655E+0	6.192E-3
/gps/hist/point 8.858E+0	4.868E-3
/gps/hist/point 9.061E+0	3.246E-3
/gps/hist/point 9.265E+0	3.488E-3
/gps/hist/point 9.468E+0	3.704E-3
/gps/hist/point 9.671E+0	4.851E-3
/gps/hist/point 9.875E+0	6.872E-3
/gps/hist/point 1.008E+1	6.107E-3
/gps/hist/point 1.028E+1	5.036E-3
/gps/hist/point 1.048E+1	3.162E-3
/gps/hist/point 1.069E+1	1.927E-3
/gps/hist/point 1.089E+1	5.609E-4
/gps/hist/point 1.100E+1	0.000E+0

#/gps/source/list


#AMBE GAMMA SOURCE
#------------------------------------------------------------------------
#TO-DO: Add a second source with GPS that emits the gamma spectrum of AmBe
#/gps/number 2          #does it matter if gps/number or /gps/source/add is called first?
#/gps/source/add 1
#/gps/number 2
#/gps/particle gamma        #beam particle
#/gps/position 0 0 -1 cm     #GPS position
#/gps/direction 0 0 1        #oriented along the Z axis

#/gps/source/list