place; 4; command=place; object=cube; name=shield; material=carbon; pos_x=0.0; pos_y=0.0; pos_z=0.0; rot_x=0.0; rot_y=0.0; rot_z=0.0; size_x=10.0; size_y=10.0; size_z=45.0; 
place; 4; command=place; object=sphere; name=source_marker; material=vacuum; pos_x=0.0; pos_y=0.0; pos_z=-50.0; rot_x=0.0; rot_y=0.0; rot_z=0.0; radius=2.0; alpha=0.5; red=0; green=100; 
place; 4; command=place; object=sphere; name=surround; material=vacuum; pos_x=0.0; pos_y=0.0; pos_z=0.0; rot_x=0.0; rot_y=0.0; rot_z=0.0; radius=200.0; inner_radius=190.0; alpha=0.2; red=100; green=0; 
place; 4; command=place; object=cube; name=detector; material=vacuum; pos_x=0.0; pos_y=0.0; pos_z=100.0; rot_x=0.0; rot_y=0.0; rot_z=0.0; size_x=10.0; size_y=10.0; size_z=0.005; 
make_sd; 5; command=make_sd; attach=ldetector; name=behind_shield; particle=primary; attrib_0=ekin; attrib_count=1; 
particle_source; 4; command=particle_source; particle=neutron; mono_e=true; shape=beam; energy=28.0; sigma=0.0; x_pos=0; y_pos=0.0; z_pos=-50.0; x_facing=0; y_facing=0; z_facing=1; sigma_r=0.4; atomic_number=0; atomic_mass=0; charge=0; excitation=0; 
no_macro_f; 1; command=no_macro_f; event_count=100000.0; thread_count=8; 
