# To be run preferably in batch, without graphics:
# ./How-To-Geant4 run.mac
#

#Silence hadronic process summary (works in Geant4 v10.7.1)
#/control/verbose 0
#/run/verbose 0
#/process/had/verbose 0
#/process/verbose 0
#/process/em/verbose 0

#/custom/GDML/loadFile Test0.gdml
#/custom/GDML/LoadOnly true
#/custom/GDML/writeFile Test0.gdml

#Set number of worker threads and initialize run
/run/numberOfThreads 8
/run/initialize

#BEAM
#------------------------------------------------------------------------
#execute the macro file which defines the primary particle
#/control/execute ../Macros/Primary_Alpha.mac        #52 MeV Alpha Beam, point source
#/control/execute ../Macros/Primary_Deuteron.mac     #26 MeV Deuteron Beam, point source
/control/execute ../Macros/Primary_Neutron.mac      #13 MeV Neutron Beam, point source
#/control/execute ../Macros/Primary_Proton.mac       #13 MeV Proton Beam, point source
#/control/execute ../Macros/Primary_AmBe.mac         #AmBe Neutron Source, point source
#/control/execute ../Macros/Primary_Radionuclide.mac #Radionuclide Source, point source
#/control/execute ../Macros/Primary_Nitrogen.mac        #17N5+ Nitrogen beam, point source

#CUSTOM COMMANDS
#------------------------------------------------------------------------
#custom commands to change things
#/custom/geo/change_a 15 cm
#/custom/geo/change_b 15 cm
#/custom/geo/change_c 15 cm
#/custom/geo/change_d 15 cm
#/custom/geo/change_e 15 cm
#/custom/geo/setMat G4_AIR
#/custom/ana/setOutFolder Output/Energy_N_100MeV_SEM

/gps/position 0 0 0 cm     #GPS position
#/custom/ana/setOutFolder Output/tny_N_AmBe_Iso

#/custom/geo/setDummyMat1 G4_Al
#/custom/geo/setDummyMat1 G4_Fe
#/custom/geo/setDummyMat1 G4_Pb
/custom/geo/setDummyMat1 G4_W
#/custom/geo/setDummyMat1 G4_CONCRETE

#/custom/ana/setOutFolder Output/nbs_1_MeV_G4_Al
#/custom/ana/setOutFolder Output/nbs_1_MeV_G4_Fe
#/custom/ana/setOutFolder Output/nbs_1_MeV_G4_Pb
#/custom/ana/setOutFolder Output/nbs_1_MeV_G4_W
#/custom/ana/setOutFolder Output/nbs_1_MeV_G4_CONCRETE
#/custom/ana/setOutFolder Output/nbs_1_MeV_G4_BoratedPE

#/custom/ana/setOutFolder Output/nbs_10_MeV_G4_Al
#/custom/ana/setOutFolder Output/nbs_10_MeV_G4_Fe
#/custom/ana/setOutFolder Output/nbs_10_MeV_G4_Pb
/custom/ana/setOutFolder Output/nbs_10_MeV_G4_W
#/custom/ana/setOutFolder Output/nbs_10_MeV_G4_CONCRETE
#/custom/ana/setOutFolder Output/nbs_10_MeV_BoratedPE


#START RUN
#------------------------------------------------------------------------
#Start a run and print progress in console
/run/printProgress 1000
/run/beamOn 100000

#max value for beam On is 2.147.483.647 because this is the maximum value for a 32 bit integer
