#
# Macro file for "Activation.cc"
#
#Silence hadronic process summary (works in Geant4 v10.7.1)
/control/verbose 0
/run/verbose 0
/process/had/verbose 0
/process/verbose 0
/process/em/verbose 0
#
/custom/det/setMat G4_Co
/custom/det/setThickness 1 cm
/custom/det/setSizeYZ 1 cm
#
#Set number o worker threads and initialize run
/run/numberOfThreads 4
/run/initialize
#
#/process/list
#

#Particle Gun commands
#/gun/particle neutron
#/gun/energy 25 meV
#/custom/gun/beamSize 8 mm
#/custom/gun/beamTime 10 year

#Commands to use with the General Particle Source (GPS)
/gps/particle neutron     #beam particle
/gps/position 0 0 0      #GPS position
/gps/direction 0 0 1     #oriented along the Z axis
/gps/ene/type Mono       #monoenergetic:   I=E
/gps/ene/mono 25 meV   #sets energy for monoenergetic sources
#/gps/pos/type Point
#
#/analysis/setFileName Co60
#/analysis/h1/set 4  100  0  8  MeV    #gamma
#/analysis/h1/set 14 100  0 20  year   #gamma
#/analysis/h1/set 24 100  0 20  year   #(Co60)
#/analysis/h1/set 25 100  0 20  year   #(Ni60)
#/analysis/h1/set 26 100  0 20  year   #(Co59)
#
/run/printProgress 10000
/run/beamOn 100001
